trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  azureWebAppName: 'easyaccess-api-final' 

stages:
- stage: CI
  displayName: 'Estágio de Integração Contínua (CI)'
  jobs:
  - job: BuildAndTest
    displayName: 'Compilação e Testes Automatizados'
    steps:
    - task: UseDotNet@2
      displayName: 'Instalar .NET 8 SDK'
      inputs:
        packageType: 'sdk'
        version: '8.x'

    - script: dotnet restore
      displayName: 'Restaurar Dependências NuGet'

    - script: dotnet build --configuration $(buildConfiguration)
      displayName: 'Compilar Solução (.NET Build)'

    - script: dotnet test --configuration $(buildConfiguration) --logger trx
      displayName: 'Executar Testes de Unidade (xUnit)'

    - task: DotNetCoreCLI@2
      displayName: 'Publicar Artefatos da API (Publish)'
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/publish'
        zipAfterPublish: false

    - task: PublishBuildArtifacts@1
      displayName: 'Disponibilizar Artefato para o CD'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/publish'
        ArtifactName: 'webfiles'
        publishLocation: 'Container'

- stage: CD
  displayName: 'Estágio de Entrega Contínua (CD)'
  dependsOn: CI
  condition: succeeded()
  jobs:
  - job: Deploy
    displayName: 'Deploy Real para o Azure App Service'
    steps:
    - task: DownloadBuildArtifacts@0
      displayName: 'Baixar Artefatos do CI'
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'webfiles'
        downloadPath: '$(System.ArtifactsDirectory)'

    - task: AzureWebApp@1
      displayName: 'Executar Deploy no Azure Web App'
      inputs:
        azureSubscription: 'ConexaoAzure'
        appType: 'webAppLinux'
        appName: '$(azureWebAppName)'
        package: '$(System.ArtifactsDirectory)/webfiles'
        # 💡 FORÇA O DEPLOY DIRETO NO AMBIENTE PRINCIPAL (Bloqueia slots temporários)
        deployToSlotOrASE: false